import fitz
import sys
import pandas as pd


FILE_PATH = "C:/Users/paulocm/Downloads/Alcaldias/PLAN DE DESARROLLO 2024 - 2027 chía preliminar.pdf" 

pdf= fitz.open(FILE_PATH)

"""a=pdf.page_count #page count
contenido=pdf.load_page(1).get_text().replace("\t","") # get the text of a specific page
print (contenido)  #print the text gotten from the pdf

num_paginas =pdf.page_count
#contenido_libro=[]

for i in range(0,num_paginas):
    pagina= pdf[i]
    #palabra="CAPÍTULO"
    lista_palabras = ["seguridad","tecnología para la seguridad", "cámaras", "drones","analítica","datos","sofware", "monitoreo","recolección de datos","inspectores","policia","seguridad en el transporte público","víctimas","delitos"]
    for palabra in lista_palabras:
        resultado=pagina.search_for(palabra, quads=True)
        pagina.add_highlight_annot(resultado)#pagina.add_highlight_annot(resultado)
pdf.save("C:/Users/paulocm/Downloads/Alcaldias/salidadocumento1.pdf")"""

#--------------------------------------

"""import fitz  # PyMuPDF

def highlight_paragraphs_with_words(pdf_path, words_to_highlight, paragraph_color):
    # Open the PDF file
    pdf_document = fitz.open(pdf_path)

    # Iterate through each page in the PDF
    for page_number in range(len(pdf_document)):
        page = pdf_document.load_page(page_number)

        # Extract text from the page
        text = page.get_text()

        # Split the text into paragraphs
        paragraphs = text.split('.')

        # Iterate through each paragraph in the page
        for paragraph in paragraphs:
            # Check if any word in the paragraph matches the words to highlight
            for word_list in words_to_highlight.values():
                for word in word_list:
                    if word.lower() in paragraph.lower():
                        # Highlight the entire paragraph
                        rect = page.search_for(paragraph)
                        highlight = page.add_highlight_annot(rect)

                        # Set the fill color for the paragraph highlight
                        highlight.set_colors({'fill': paragraph_color})

                        # Break out of the loop once a match is found
                        break
                else:
                    continue
                break

    # Save the modified PDF file
    pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/highlighted_pdf.pdf')

    # Close the PDF document
    pdf_document.close()

pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/PLAN DE DESARROLLO 2024 - 2027 chía preliminar.pdf'
words_to_highlight = {
    'Tecnología para la seguridad (Camaras - drones..)': ['seguridad', 'tecnología', 'tecnología para la seguridad','cámaras','drones'],
    'Analítica de datos (sofware, monitoreo y evaluación, recolección datos)': ['analítica','analítica de datos','software','monitoreo'],
    'Inspectores de policía': ['inspectores de policía','inspectores','policía'],
    'Seguridad en el transporte público': ['seguridad en el transporte público','transporte público'],
    'Víctimas de delitos': ['víctimas de delitos','víctimas','delitos'],
    'Línea de atención de emergencia ': ['línea de atención de emergencia','línea de atención de emergencias','línea de emergencias','atención de emergencias'],
    'Entornos escolares seguros': ['entornos escolares seguros','entornos escolares'],
    'Investigación criminal y judicializacion': ['investigación criminal y judicializacion' ,'investigación criminal','judicializacion'],
    'Cuadrantes y gestión policial (seguridad territorial, local, barrial)': ['cuadrante','cuadrantes', 'gestión policial','seguridad territorial', 'seguridad local', 'seguridad barrial'],
    'Mecanismos de denuncia': ['mecanismos de denuncia','mecanismo de denuncia', 'denuncia'],
    'Ciberseguridad y ciberdelitos': ['ciberseguridad', 'ciberdelito'],
    'cais y estaciones de policías': ['estaciones de policías', 'cai','estación de policía','estación de policías'],
    'Capacitación y formación fuerza pública': ['capacitación y formación de fuerza pública', 'capacitación de fuerza pública','formación de fuerza pública','capacitar a la fuerza pública','formar a la fuerza pública','capacitar policia','formar policia','capacitar a la policia','formar a la policia'],
    'fortalecimiento y acciones para implementar el Código de Policía': ['código de policía'],
    'Prevención y reducción de Muertes violentas (Homicidios, suicidios, accidentes de transito)': ['prevención y reducción de muertes violentas','prevención de muertes violentas','reducción de muertes violentas','prevenir muertes violentas','reducir muertes violentas','prevenir las muertes violentas','reducir las muertes violentas', 
                                                                                                    'prevención y reducción de homicidios','prevención de homicidios','reducción de homicidios','prevenir homicidios','reducir homicidios','prevenir los homicidios','reducir los homicidios'
                                                                                                    'prevención y reducción de suicidios','prevención de suicidioss','reducción de suicidios','prevenir suicidios','reducir suicidios','prevenir los suicidios','reducir los suicidios'
                                                                                                    'prevención y reducción de accidentes de tránsito','prevención de accidentes de tránsito','reducción de accidentes de tránsito','prevenir accidentes de tránsito','reducir accidentes de tránsito','prevenir los accidentes de tránsito','reducir los accidentes de tránsito'],
    'hurto a personas': ['hurto a personas','hurto','robo a personas'],
    'hurto a residencias': ['hurto a residencias','robo a personas'],
    'hurto a comercios': ['hurto a comercios','robo a personas'],
    'porte de armas (armas blancas y armas de fuego)': ['porte de armas','armas'],
    # Add more categories and words as needed
}
paragraph_color = (1, 0, 0)  # Red color for highlighted paragraphs

highlight_paragraphs_with_words(pdf_path, words_to_highlight, paragraph_color)"""

#------------------------------------------

import fitz  # PyMuPDF

def highlight_paragraphs_with_words(pdf_path, words_to_highlight, paragraph_color):
    # Open the PDF file
    pdf_document = fitz.open(pdf_path)

    # Iterate through each page in the PDF
    for page_number in range(len(pdf_document)):
        page = pdf_document.load_page(page_number)

        # Extract text from the page
        text = page.get_text()

        # Split the text into paragraphs
        paragraphs = text.split('.')

        # Iterate through each paragraph in the page
        for paragraph in paragraphs:
            # Check if any word in the paragraph matches the words to highlight
            for word_list in words_to_highlight.values():
                for word in word_list:
                    if word.lower() in paragraph.lower():
                        # Get the rectangle coordinates for the paragraph
                        rect = page.search_for(paragraph)

                        # Draw a square over the paragraph
                        for r in rect:
                            # Add a rectangle annotation
                            annot = page.add_rect_annot(r)

                            # Set the color of the rectangle annotation
                            annot.set_colors(stroke=paragraph_color, fill=paragraph_color)
                          
                        # Break out of the loop once a match is found
                        break
                else:
                    continue
                break

    # Save the modified PDF file
    #pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesBogota_pdf.pdf')
    #pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesCajica_pdf.pdf')
    #pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesChia2_pdf.pdf')
    #pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesSopo_pdf.pdf')
    #pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesBogota2_pdf.pdf')
    pdf_document.save('C:/Users/paulocm/Downloads/Alcaldias/rectanglesCajica2_pdf.pdf')

    # Close the PDF document
    pdf_document.close()

#pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/PROYECTO DE ACUERDO - PDD 2024 - 2028-versionfinal.pdf'
#pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/DOCUMENTO TÉCNICO PDM CAJICA.pdf'
#pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/Proyecto de Acuerdo Plan de Desarrollo (Chía) abril 2024.pdf'
#pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/Proyecto de Acuerdo Plan de Desarrollo SOPÓ, CUENTA CONTIGO 2024-2027.pdf'
#pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/PROYECTO DE ACUERDO - PDD 2024 - 2028_versionfinal.pdf'
pdf_path = 'C:/Users/paulocm/Downloads/Alcaldias/PROYECTO DE ACUERDO FINAL CAJICÁ ENTREGA 29 ABRIL.pdf'

words_to_highlight = {
    'Tecnología para la seguridad (Camaras - drones..)': ['Seguridad', 'seguridad', 'Tecnología para la seguridad','tecnología para la seguridad','Cámaras','cámaras','Drones','drones'],
    'Analítica de datos (sofware, monitoreo y evaluación, recolección datos)': ['Analítica','analítica','Analítica de datos','analítica de datos','Software','software','Monitoreo','monitoreo'],
    'Inspectores de policía': ['Inspectores de policía','inspectores de policía','Inspectores','inspectores','Policía','policía'],
    'Seguridad en el transporte público': ['Seguridad en el transporte público','seguridad en el transporte público','Transporte público','transporte público'],
    'Víctimas de delitos': ['Víctimas de delitos','víctimas de delitos','Víctimas','víctimas','Delitos','delitos'],
    'Línea de atención de emergencia': ['Línea de atención de emergencia','línea de atención de emergencia','Línea de atención de emergencias','línea de atención de emergencias','Línea de emergencias','línea de emergencias','Atención de emergencias','atención de emergencias'],
    'Entornos escolares seguros': ['Entornos escolares seguros','entornos escolares seguros','Entornos escolares','entornos escolares'],
    'Investigación criminal y judicializacion': ['Investigación criminal y judicializacion','investigación criminal y judicializacion','Investigación criminal','investigación criminal','Judicializacion','judicializacion'],
    'Cuadrantes y gestión policial (seguridad territorial, local, barrial)': ['Cuadrantes y gestión policial','cuadrantes y gestión policial','Seguridad territorial','seguridad territorial','Seguridad local','seguridad local','Seguridad barrial','seguridad barrial'],
    'Mecanismos de denuncia': ['Mecanismos de denuncia','mecanismos de denuncia','Mecanismo de denuncia','mecanismo de denuncia','Denuncia','denuncia'],
    'Ciberseguridad y ciberdelitos': ['Ciberseguridad y ciberdelitos','ciberseguridad y ciberdelitos','Ciberseguridad','ciberseguridad','Ciberdelito','ciberdelito'],
    'cais y estaciones de policías': ['Estaciones de policías','estaciones de policías','Cai','cai','Estación de policía','estación de policía','Estación de policías','estación de policías'],
    'Capacitación y formación fuerza pública': ['Capacitación y formación de fuerza pública','capacitación y formación de fuerza pública','Capacitación de fuerza pública','capacitación de fuerza pública','Formación de fuerza pública','formación de fuerza pública','Capacitar a la fuerza pública','capacitar a la fuerza pública','Formar a la fuerza pública','formar a la fuerza pública','Capacitar policía','capacitar policía','Formar policía','formar policía','Capacitar a la policía','capacitar a la policía','Formar a la policía','formar a la policía'],
    'fortalecimiento y acciones para implementar el Código de Policía': ['Código de policía','código de policía'],
    'Prevención y reducción de Muertes violentas (Homicidios, suicidios, accidentes de transito)': ['Prevención y reducción de muertes violentas','prevención y reducción de muertes violentas','Prevención de muertes violentas','prevención de muertes violentas','Reducción de muertes violentas','reducción de muertes violentas','Prevenir muertes violentas','prevenir muertes violentas','Reducir muertes violentas','reducir muertes violentas','Prevenir las muertes violentas','prevenir las muertes violentas','Reducir las muertes violentas','reducir las muertes violentas','Prevención y reducción de homicidios','prevención y reducción de homicidios','Prevención de homicidios','prevención de homicidios','Reducción de homicidios','reducción de homicidios','Prevenir homicidios','prevenir homicidios','Reducir homicidios','reducir homicidios','Prevenir los homicidios','prevenir los homicidios','Reducir los homicidios','reducir los homicidios','Prevención y reducción de suicidios','prevención y reducción de suicidios','Prevención de suicidioss','prevención de suicidioss','Reducción de suicidios','reducción de suicidios','Prevenir suicidios','prevenir suicidios','Reducir suicidios','reducir suicidios','Prevenir los suicidios','prevenir los suicidios','Reducir los suicidios','reducir los suicidios','Prevención y reducción de accidentes de tránsito','prevención y reducción de accidentes de tránsito','Prevención de accidentes de tránsito','prevención de accidentes de tránsito','Reducción de accidentes de tránsito','reducción de accidentes de tránsito','Prevenir accidentes de tránsito','prevenir accidentes de tránsito','Reducir accidentes de tránsito','reducir accidentes de tránsito','Prevenir los accidentes de tránsito','prevenir los accidentes de tránsito','Reducir los accidentes de tránsito','reducir los accidentes de tránsito'],
    'hurto a personas': ['Hurto a personas','hurto a personas','Hurto','hurto','Robo a personas','robo a personas'],
    'hurto a residencias': ['Hurto a residencias','hurto a residencias','Robo a personas','robo a personas'],
    'hurto a comercios': ['Hurto a comercios','hurto a comercios','Robo a personas','robo a personas'],
    'porte de armas (armas blancas y armas de fuego)': ['Porte de armas','porte de armas','Armas','armas','Arma','arma'],
    'Cultura Ciudadana para la convivencia':['Cultura Ciudadana para la convivencia','cultura ciudadana para la convivencia','Cultura Ciudadana','cultura ciudadana','Convivencia','convivencia'],
    'Resolución de conflictos':['Resolución de conflictos','resolución de conflictos','Resolver conflictos','resolver conflictos'],
    'Violencias basadas en Género':['Violencias basadas en Género','violencias basadas en género','Violencia de género','violencia de género','Violencias de género','violencias de género','Violencia a las mujeres','violencia a las mujeres','Violencia a la mujer','violencia a la mujer'],
    'Violencia intrafamiliar':['Violencia intrafamiliar','violencia intrafamiliar','Violencia al interior de la familia','violencia al interior de la familia','maltrato infantil', 'Maltrato infantil','violencia sexual','Violencia sexual'],
    'Violencia contra Adulto mayor o tercera edad':['Violencia contra Adulto mayor o tercera edad','violencia contra adulto mayor o tercera edad','Violencia contra el adulto mayor','violencia contra el adulto mayor','Violencia contra las personas de tercera edad','violencia contra las personas de tercera edad','Violencia contra los adultos mayores','violencia contra los adultos mayores','Violencia contra adultos mayores','violencia contra adultos mayores','Violencia a los adultos mayores','violencia a los adultos mayores','Violencia a los de tercera edad','violencia a los de tercera edad','Violencia contra el anciano','violencia contra el anciano','Violencia contra los ancianos','violencia contra los ancianos','Violencia al anciano','violencia al anciano','Violencia a los ancianos','violencia a los ancianos'],
    'Lesiones personales o Riñas':['Lesiones personales o Riñas','lesiones personales o riñas','Lesiones personales','lesiones personales','Riñas','riñas','Lesión personal','lesión personal','Riña','riña'],
    'Comisarías de familia':['Comisarías de familia','comisarías de familia','Comisaría de familia','comisaría de familia'],
    'Educación para la paz':['Educación para la paz','educación para la paz','Educación y paz','educación y paz','Educar para la paz','educar para la paz'],
    'Convivencia en Propiedad horizontal':['Convivencia en Propiedad horizontal','convivencia en propiedad horizontal','Convivencia en edificio','convivencia en edificio','Convivencia en las propiedades horizontales','convivencia en las propiedades horizontales','Convivencia en los edificios','convivencia en los edificios'],
    'consumo de SPA':['consumo de SPA','consumo de spa','Sustancias psicoactivas','sustancias psicoactivas','Consumo de drogas','consumo de drogas','Consumo de sustancias psicoactivas','consumo de sustancias psicoactivas'],
    'Derechos Humanos':['Derechos Humanos','derechos humanos'],
    'Movilidad sostenible (Patinetas eléctricas, a pie, bicicletas, Ciclorutas, otros)':['Movilidad sostenible','movilidad sostenible','Patineta eléctrica','patineta eléctrica','Patinetas eléctricas','patinetas eléctricas','A pie','a pie','Bicicleta','bicicleta', 'Cicla','cicla','Ciclorruta','ciclorruta','Ciclovía','ciclovía','Auto eléctrico','auto eléctrico','Carro eléctrico','carro eléctrico'],
    'Seguridad vial (siniestros, muertes, cultura vial)':['Seguridad vial','seguridad vial','Seguridad en la vía','seguridad en la vía','Accidentes de tráfico','accidentes de tráfico','Accidentes de tránsito','accidentes de tránsito','Siniestros de tráfico','siniestros de tráfico','Siniestros de tránsito','siniestros de tránsito','Muertes en la vía','muertes en la vía','Muertes en carretera','muertes en carretera','Muertes en la carretera','muertes en la carretera','Cultura vial','cultura vial','Cultura en la vía','cultura en la vía','Peatón','peatón','Peatones','peatones','Conductores','conductores'],
    'Accesos y salidas del municipio':['Accesos y salidas del municipio','accesos y salidas del municipio','Acceso al municipio','acceso al municipio','Salida del municipio','salida del municipio','Ingreso al municipio','ingreso al municipio','Vía de acceso','vía de acceso','malla vial','Malla vial','nueva salida de la ciudad','Nueva salida de la ciudad','nuevas salidas de la ciudad','Nuevas salidas de la ciudad','nueva salida del municipio','Nueva salida del municipio','nuevas salidas del municipio','Nuevas salidas del municipio'],
    'Comportamiento víal y la cultura ciudadana':['Comportamiento vial y la cultura ciudadana','comportamiento vial y la cultura ciudadana','Comportamiento vial','comportamiento vial','Cultura vial','cultura vial','seguridad vial','Seguridad vial'],
    'Infraestructura vial para el peatón y ciclista':['Infraestructura vial para el peatón y ciclista','infraestructura vial para el peatón y ciclista','Andén','andén','Andenes','andenes','Ciclorruta','ciclorruta','Ciclovía','ciclovía','Puente peatonal','puente peatonal','Puentes peatonales','puentes peatonales','movilidad activa','caminata','bicicleta','cicla','Movilidad activa','Caminata','Bicicleta','Cicla'],
    'Infraestructura vial para vehículos':['Infraestructura vial para vehículos','infraestructura vial para vehículos','Infraestructura vial para carros','infraestructura vial para carros','Carretera','carretera','Autopista','autopista','Puente de carros','puente de carros','Puente de autos','puente de autos','Túnel','túnel','malla vial','Malla vial'],
    'Gestión de tráfico (semaforización, señaletica, paraderos, cebras y cruces, rutas )':['Gestión de tráfico','gestión de tráfico','Semaforización','semaforización','Semáforo','semáforo','Señal de tráfico','señal de tráfico','Señal de tránsito','señal de tránsito','Señales de tráfico','señales de tráfico','Señales de tránsito','señales de tránsito','Señalética','señalética','Paradero','paradero','Parqueadero','parqueadero','Cebra','cebra','Cruce vial','cruce vial', 'Cruces viales','cruces viales'],
    'Logística y carga':['Logística y carga','logística y carga','Logística','logística','Tráfico de carga','tráfico de carga'],
    'Transporte informal (bicitaxis, rutas informales)':['Transporte informal','transporte informal','Bicitaxi','bicitaxi','Mototaxi','mototaxi','Rutas informales','rutas informales'],
    'Movilidad inclusiva y accesibilidad usuarios especiales (rampas, ayudas…)':['Movilidad inclusiva y accesibilidad usuarios especiales','movilidad inclusiva y accesibilidad usuarios especiales','Accesibilidad','accesibilidad','Diseño universal','diseño universal', 'Rampas','rampas','Acceso a personas con necesidades especiales','acceso a personas con necesidades especiales', 'Acceso a usuarios especiales','acceso a usuarios especiales'],
    'Terminal de transporte':['Terminal de transporte','terminal de transporte', 'Terminales de transporte','terminales de transporte'],
    'Brechas en el aprendizaje - desigualdad educativa':['Brechas en el aprendizaje - desigualdad educativa','brechas en el aprendizaje - desigualdad educativa','Brechas del aprendizaje','brechas del aprendizaje','Brecha educativa','brecha educativa','Disparidad educativa','disparidad educativa','Desigualdad educativa','desigualdad educativa'],
    'Deserción escolar':['Deserción escolar','deserción escolar','Deserción educativa','deserción educativa','Abandono educativo','abandono educativo','Abandono escolar','abandono escolar','Desvinculación escolar','desvinculación escolar'],
    'Jornada escolar (Jornada Única y jornada complementaria)':['Jornada escolar','jornada escolar','Jornada única','jornada única','Jornada complementaria','jornada complementaria)'],
    'Infraestructura educativa':['Infraestructura educativa','infraestructura educativa', 'Infraestructura académica','infraestructura académica','Colegio','colegio','Universidad','universidad','Aula de clase','aula de clase','Aulas de clase','aulas de clase','Salón de clase','salón de clase','Salones de clase','salones de clase','Laboratorio','laboratorio','Escuela','escuela'],
    'Recursos humanos (Docentes, administrativos, personal de apoyo)':['Recursos humanos','recursos humanos','Docente','docente','Profesor','profesor','Administrativo','administrativo', 'Personal de apoyo','personal de apoyo'],
    'Educación inicial y primera infancia':['Educación inicial y primera infancia','educación inicial y primera infancia','Primera infancia','primera infancia','Jardín','jardín','Educación preescolar','educación preescolar','Preescolar','preescolar'],
    'Alimentación escolar':['Alimentación escolar','alimentación escolar','Alimentación Escolar','Dieta escolar','dieta escolar','Alimentación para los niños','alimentación para los niños','Asistencia alimentaria','asistencia alimentaria','Comedor escolar','comedor escolar'],
    'Bienestar estudiantil':['Bienestar estudiantil','bienestar estudiantil','Bienestar del estudiante','bienestar del estudiante','Bienestar del alumno','bienestar del alumno','estilo de vida saludable','Estilo de vida saludable'],
    'Formación y capacitación docente':['Formación y capacitación docente','formación y capacitación docente','Formación docente','formación docente','Capacitación docente','capacitación docente','Formación del docente','formación del docente','Capacitación del docente','capacitación del docente','Formación del profesor','formación del profesor', 'Formación del profesorado','formación del profesorado','Capacitación del profesorado','capacitación del profesorado','Formación de los docentes','formación de los docentes','Capacitación de los docentes','capacitación de los docentes','Formación de los profesores','formación de los profesores','Capacitación de los profesores','capacitación de los profesores'],
    'Educación superior (universitaria, técnica y tecnologica)':['Educación superior','educación superior','Educación universitaria','educación universitaria','Educación técnica','educación técnica', 'Educación tecnológica','educación tecnológica', 'Educación técnica y tecnológica','educación técnica y tecnológica','Educación profesional','educación profesional','Pregrado','pregrado'],
    'Investigación, desarrollo e innovación':['Investigación, desarrollo e innovación','investigación, desarrollo e innovación','I+D','i+d','Investigación y desarrollo','investigación y desarrollo','Innovación','innovación'],
    'Bilingüismo':['Bilingüismo','bilingüismo','Bilingue','bilingue','Lenguas','lenguas','Enseñanza de lenguas','enseñanza de lenguas'],
    'Inclusión y enfoque diferencial':['Inclusión y enfoque diferencial','inclusión y enfoque diferencial','Inclusión','inclusión','Enfoque diferencial','enfoque diferencial'],
    'Transformación digital':['Transformación digital','transformación digital','Adopción digital','adopción digital','Adopción tecnológica','adopción tecnológica','Tics','tics'],
    'Convivencia Escolar':['Convivencia Escolar','convivencia escolar','Comunidad educativa','comunidad educativa'],
    'Transporte escolar':['Transporte escolar','transporte escolar','Bus escolar','bus escolar', 'Ruta escolar','ruta escolar'],    
    'Participación de Padres de Familia / Gobierno Escolar': ['participación de padres de familia', 'Participación de padres de familia', 'Asociación de padres de familia', 'asociación de padres de familia', 'Padres de familia', 'padres de familia', 'Gobierno escolar', 'gobierno escolar', 'Gobierno estudiantil', 'gobierno estudiantil', 'Directivos educativos', 'directivos educativos', 'Comité escolar', 'comité escolar', 'Comités escolares', 'comités escolares'],
    'Becas y Apoyos Económicos': ['becas y apoyos económicos', 'Becas y apoyos económicos', 'Beca', 'beca', 'Auxilio educativo', 'auxilio educativo', 'Auxilios educativos', 'auxilios educativos', 'Patrocinio educativo', 'patrocinio educativo', 'Apoyo económico', 'apoyo económico', 'Apoyos económicos', 'apoyos económicos','oferta de financiación','Oferta de financiación','ofertas de financiación','Ofertas de financiación','mecanismo alternativo de recursos','Mecanismo alternativo de recursos','mecanismos alternativo de recursos','Mecanismos alternativo de recursos'],
    'Matrícula y Cobertura': ['matrícula', 'Matrícula', 'Cobertura educativa', 'cobertura educativa', 'Cubrimiento educativo', 'cubrimiento educativo', 'Cobertura escolar', 'cobertura escolar', 'Cubrimiento escolar', 'cubrimiento escolar','cupo escolar','Cupo escolar','cupos escolares','Cupos escolares','ampliación del tiempo escolar','Ampliación del tiempo escolar'],
    'Repitencia': ['repitencia', 'Repitencia', 'Repitente', 'repitente'],
    'Atención Primaria en Salud-  APS': ['atención primaria', 'Atención primaria','Atención Primaria', 'Atención en salud', 'atención en salud', 'Atención de salud', 'atención de salud', 'Atención prioritaria', 'atención prioritaria', 'Atención de urgencia', 'atención de urgencia', 'Atención en urgencia', 'atención en urgencia'],
    'Acceso a servicios de salud / Aseguramiento y cobertura': ['acceso a servicios de salud', 'Acceso a servicios de salud', 'aseguramiento y cobertura', 'Aseguramiento y cobertura', 'acceso a salud', 'Acceso a salud', 'acceso a la salud', 'Acceso a la salud', 'servicios de salud', 'Servicios de salud', 'servicios para la salud', 'Servicios para la salud', 'aseguramiento en salud', 'Aseguramiento en salud', 'aseguramiento de salud', 'Aseguramiento de salud', 'cobertura de salud', 'Cobertura de salud', 'cobertura en salud', 'Cobertura en salud'],
    'Infraestructura física (puestos de salud, hospitales, centros especializados)': ['infraestructura de salud', 'Infraestructura de salud', 'infraestructura en salud', 'Infraestructura en salud', 'puesto de salud', 'Puesto de salud', 'puestos en salud', 'Puestos en salud', 'hospital', 'Hospital', 'centro de salud', 'Centro de salud', 'centros de salud', 'Centros de salud', 'clínica', 'Clínica', 'centro especializado', 'Centro especializado', 'centros especializados', 'Centros especializados'],
    'Infraestructura hospitalaria (instalaciones, equipamiento, camas)': ['infraestructura hospitalaria', 'Infraestructura hospitalaria', 'instalación hospitalaria', 'Instalación hospitalaria', 'instalaciones hospitalarias', 'Instalaciones hospitalarias', 'equipamiento hospitalario', 'Equipamiento hospitalario', 'equipamientos hospitalarios', 'Equipamientos hospitalarios', 'equipamento en hospital', 'Equipamento en hospital', 'camas', 'Camas', 'consultorio', 'Consultorio', 'equipamento especializado', 'Equipamento especializado', 'silla de ruedas', 'Silla de ruedas', 'sillas de ruedas', 'Sillas de ruedas'],
    'Salud mental': ['salud mental', 'Salud mental', 'bienestar mental', 'Bienestar mental', 'estado mental', 'Estado mental', 'trastorno mental', 'Trastorno mental', 'enfermedad mental', 'Enfermedad mental', 'transtornos mentales', 'Transtornos mentales', 'enfermedades mentales', 'Enfermedades mentales'],
    'Salud sexual y reproductiva (Prevención VIH)': ['salud sexual', 'Salud sexual', 'salud reproductiva', 'Salud reproductiva', 'bienestar sexual', 'Bienestar sexual', 'bienestar reproductivo', 'Bienestar reproductivo', 'enfermedad de transmisión sexual', 'Enfermedad de transmisión sexual', 'enfermedades de transmisión sexual', 'Enfermedades de transmisión sexual', 'ets', 'ETS', 'prevención de vih', 'Prevención de VIH', 'papiloma humano', 'Papiloma humano', 'anticoncepción', 'Anticoncepción', 'anticonceptivo', 'Anticonceptivo'],
    'Vigilancia y control sanitario': ['vigilancia y control sanitario', 'Vigilancia y control sanitario', 'vigilancia sanitaria', 'Vigilancia sanitaria', 'control sanitario', 'Control sanitario', 'controles sanitarios', 'Controles sanitarios', 'problema sanitario', 'Problema sanitario', 'problemas sanitarios', 'Problemas sanitarios', 'salud pública', 'Salud pública'],
    'Lactancia materna': ['lactancia materna', 'Lactancia materna', 'lactancia', 'Lactancia', 'alimentación en bebés', 'Alimentación en bebés', 'alimentación en recién nacidos', 'Alimentación en recién nacidos', 'seno de la madre', 'Seno de la madre', 'lactante', 'Lactante'],
    'Mujeres gestantes / embarazo adolescente': ['mujeres gestantes', 'Mujeres gestantes', 'en embarazo', 'En embarazo', 'estado de embarazo', 'Estado de embarazo', 'encinta', 'Encinta', 'gestación', 'Gestación', 'embarazo adolescente', 'Embarazo adolescente', 'embarazo a corta edad', 'Embarazo a corta edad', 'embarazo en edad escolar', 'Embarazo en edad escolar', 'embarazo precoz', 'Embarazo precoz', 'aborto', 'Aborto', 'abortar', 'Abortar'],
    'Recursos Humanos en salud': ['recursos humanos en salud', 'Recursos humanos en salud', 'recurso humano en salud', 'Recurso humano en salud', 'personal de salud', 'Personal de salud', 'doctor', 'Doctor', 'médico', 'Médico', 'enfermero', 'Enfermero', 'enfermera', 'Enfermera', 'administrativo en salud', 'Administrativo en salud', 'administrativo de salud', 'Administrativo de salud', 'especialista en salud', 'Especialista en salud', 'especialista de salud', 'Especialista de salud'],
    'Vacunación': ['vacunación', 'Vacunación', 'vacuna', 'Vacuna', 'inmunización', 'Inmunización', 'inmuniza', 'Inmuniza', 'inocular', 'Inocular', 'inocula', 'Inocula'],
    'Mortalidad materna e infantil': ['mortalidad materna', 'Mortalidad materna', 'mortalidad infantil', 'Mortalidad infantil', 'mortalidad en madres', 'Mortalidad en madres', 'mortalidad en niños', 'Mortalidad en niños', 'mortalidad en gestantes', 'Mortalidad en gestantes', 'mortalidad de recién nacidos', 'Mortalidad de recién nacidos', 'muerte de madres', 'Muerte de madres', 'muerte en madres', 'Muerte en madres', 'muerte materna', 'Muerte materna', 'muerte de niños', 'Muerte de niños', 'muerte en gestantes', 'Muerte en gestantes', 'muerte en niños', 'Muerte en niños', 'muerte en infantes', 'Muerte en infantes', 'muerte de infantes', 'Muerte de infantes', 'muerte infantil', 'Muerte infantil','salud materna', 'Salud materna','salud infantil','Salud infantil','salud materno','Salud materno'],
    'Nutrición (prevalencia peso al nacer, desnutrición crónica y desnutrición global)': ['nutrición', 'Nutrición', 'desnutrición', 'Desnutrición', 'peso al nacer', 'Peso al nacer', 'alimentación', 'Alimentación'],
    'Transición energética': ['transición energética', 'Transición energética', 'transformación energética', 'Transformación energética', 'energía renovable', 'Energía renovable', 'energías renovables', 'Energías renovables', 'descarbonización', 'Descarbonización', 'reducción de emisiones', 'Reducción de emisiones', 'reducción de co', 'Reducción de co', 'emisiones de co', 'Emisiones de co', 'reducción de gases de efecto invernadero', 'Reducción de gases de efecto invernadero', 'energía límpia', 'Energía límpia', 'energías limpias', 'Energías limpias', 'sustentabilidad energética', 'Sustentabilidad energética', 'sostenibilidad energética', 'Sostenibilidad energética', 'eficiencia energética', 'Eficiencia energética'],
    'Mitigación y adaptación al cambio climático': ['mitigación y adaptación al cambio climático', 'Mitigación y adaptación al cambio climático', 'cambio climático', 'Cambio climático', 'calentamiento global', 'Calentamiento global', 'antropogénico', 'Antropogénico'],
    'Protección y restauración de ecosistemas': ['protección y restauración de ecosistemas', 'Protección y restauración de ecosistemas', 'ecosistemas', 'Ecosistemas', 'medio ambiente', 'Medio ambiente', 'medioambiental', 'Medioambiental'],
    'Economía circular (reciclaje, reaprovechamiento y reuso)': ['economía circular', 'Economía circular', 'recicla', 'Recicla', 'reaprovecha', 'Reaprovecha', 'reuso', 'Reuso', 'reusar', 'Reusar', 'ecodiseñar', 'Ecodiseñar', 'ecodiseño', 'Ecodiseño'],
    'Bienestar y protección de animales': ['bienestar y protección de animales', 'Bienestar y protección de animales', 'protección de animales', 'Protección de animales', 'protección animal', 'Protección animal', 'bienestar animal', 'Bienestar animal', 'bienestar de animales', 'Bienestar de animales', 'bienestar de los animales', 'Bienestar de los animales', 'protección de los animales', 'Protección de los animales'],
    'Calidad del aire': ['calidad del aire', 'Calidad del aire', 'aire', 'Aire', 'contaminación atmosférica', 'Contaminación atmosférica', 'polución', 'Polución'],
    'Contaminación auditiva': ['contaminación auditiva', 'Contaminación auditiva', 'contaminación acústica', 'Contaminación acústica', 'contaminación sonora', 'Contaminación sonora','emisión de ruido','Emisión de ruido','emisiones de ruido','Emisiones de ruido','emisión atmosférica','Emisión atmosférica','emisiones atmosféricas','Emisiones atmosféricas'],
    'Educación ambiental': ['educación ambiental', 'Educación ambiental', 'formación ambiental', 'Formación ambiental', 'cultura ambiental', 'Cultura ambiental', 'conciencia ambiental', 'Conciencia ambiental', 'conexión con el ambiente', 'Conexión con el ambiente', 'conexión con el medio ambiente', 'Conexión con el medio ambiente'],
    'descontaminación del Río Bogotá': ['descontaminación del río Bogotá', 'Descontaminación del río Bogotá', 'descontaminar el río Bogotá', 'Descontaminar el río Bogotá', 'purificar el río Bogotá', 'Purificar el río Bogotá', 'limpiar el río Bogotá', 'Limpiar el río Bogotá', 'limpieza del río Bogotá', 'Limpieza del río Bogotá', 'rehabilitar al río Bogotá', 'Rehabilitar al río Bogotá', 'rehabilitar el río Bogotá', 'Rehabilitar el río Bogotá','descontaminación del Río Bogotá', 'Descontaminación del Río Bogotá', 'descontaminar el Río Bogotá', 'Descontaminar el Río Bogotá', 'purificar el Río Bogotá', 'Purificar el Río Bogotá', 'limpiar el Río Bogotá', 'Limpiar el Río Bogotá', 'limpieza del Río Bogotá', 'Limpieza del Río Bogotá', 'rehabilitar al Río Bogotá', 'Rehabilitar al Río Bogotá', 'rehabilitar el Río Bogotá', 'Rehabilitar el Río Bogotá','tratamiento de aguas residuales','Tratamiento de aguas residuales','tratamientos de aguas residuales','Tratamientos de aguas residuales','saneamiento del río','Saneamiento del río','saneamientos del río','Saneamientos del río','residuo sólido','Residuo sólido','residuos sólidos','Residuos sólidos','sistema hídrico','Sistema hídrico', 'sistemas hídricos','Sistemas hídricos'],
    'Estructura ecológica principal ( Páramos, Ríos, cuencas hídricas, humedales)': ['estructura ecológica principal', 'Estructura ecológica principal', 'páramo', 'Páramo', 'río', 'Río', 'cuenca hídrica', 'Cuenca hídrica', 'cuencas hídricas', 'Cuencas hídricas', 'humedal', 'Humedal'],
    'Saneamiento y Manejo de Vertimientos': ['saneamiento y manejo de vertimientos', 'Saneamiento y manejo de vertimientos', 'vertimiento', 'Vertimiento'],
    'Arbolado e infraestructura verde': ['arbolado e infraestructura verde', 'Arbolado e infraestructura verde', 'árboles', 'Árboles', 'infraestructura verde', 'Infraestructura verde', 'reverdece', 'Reverdece', 'programa verde', 'Programa verde'],
    'Protección Flora y Fauna (biodiversidad)': ['protección flora y fauna', 'Protección flora y fauna', 'biodiversidad', 'Biodiversidad', 'flora', 'Flora', 'fauna', 'Fauna'],
    'Transferencias y subsidios': ['transferencias y subsidios', 'Transferencias y subsidios', 'transferencia', 'Transferencia', 'subsidio', 'Subsidio', 'subvención', 'Subvención', 'auxilio económico', 'Auxilio económico', 'ayuda económica', 'Ayuda económica'],
    'Seguridad Alimentaria (Reducción del hambre, comedores comunitarios, mercados)': ['seguridad alimentaria', 'Seguridad alimentaria', 'reducción de hambre', 'Reducción de hambre', 'reducción del hambre', 'Reducción del hambre', 'comedor comunitario', 'Comedor comunitario', 'mercado', 'Mercado', 'combatir el hambre', 'Combatir el hambre', 'combatiendo el hambre', 'Combatiendo el hambre', 'hambruna', 'Hambruna'],
    'Primera infancia': ['primera infancia', 'Primera infancia', 'niñez', 'Niñez', 'niños', 'Niños', 'niñas', 'Niñas', 'bebés', 'Bebés'],
    'Trabajo infantil (prevención y reducción)': ['trabajo infantil', 'Trabajo infantil', 'niños trabajando', 'Niños trabajando'],
    'Juventud': ['juventud', 'Juventud', 'política para la juventud', 'Política para la juventud', 'políticas para la juventud', 'Políticas para la juventud', 'políticas para los jóvenes', 'Políticas para los jóvenes', 'jóvenes', 'Jóvenes', 'juventudes', 'Juventudes'],
    'Habitantes de calle': ['habitantes de calle', 'Habitantes de calle', 'habitante de la calle', 'Habitante de la calle', 'habitantes de la calle', 'Habitantes de la calle', 'indigente', 'Indigente', 'reciclador', 'Reciclador'],
    'Adulto Mayor': ['adulto mayor', 'Adulto mayor', 'política para adulto mayor', 'Política para adulto mayor', 'políticas para adultos mayores', 'Políticas para adultos mayores', 'política para persona de tercera edad', 'Política para persona de tercera edad', 'políticas para personas de tercera edad', 'Políticas para personas de tercera edad', 'políticas para las personas de tercera edad', 'Políticas para las personas de tercera edad', 'política para anciano', 'Política para anciano', 'políticas para anciano', 'Políticas para anciano', 'persona de tercera edad', 'Persona de tercera edad', 'anciano', 'Anciano', 'adulto mayor', 'Adulto mayor','persona mayor','Persona mayor','personas mayores','Personas mayores'],
    'Población LGBTIQ+': ['población lgbtiq+', 'Población lgbtiq+', 'política lgbt', 'Política lgbt', 'políticas lgbt', 'Políticas lgbt', 'política sobre lgbt', 'Política sobre lgbt', 'homosexual', 'Homosexual', 'gay', 'Gay', 'lesbian', 'Lesbian', 'travesti', 'Travesti', 'bisexual', 'Bisexual'],
    'Víctimas conflicto': ['víctimas del conflicto', 'Víctimas del conflicto', 'víctimas de la guerra', 'Víctimas de la guerra', 'políticas para las víctimas', 'Políticas para las víctimas', 'víctimas del combate', 'Víctimas del combate', 'víctima del combate', 'Víctima del combate'],
    'Enfoque de género': ['enfoque de género', 'Enfoque de género', 'equidad de género','Equidad de género','perspectiva de género', 'Perspectiva de género', 'discriminación de género', 'Discriminación de género', 'discriminación por género', 'Discriminación por género', 'exclusión por género', 'Exclusión por género','niño','Niño','niña','Niña','adolescente','Adolescente','niños, niñas y adolescentes','Niños, niñas y adolescentes','niños, niñas y madres','orientación sexual','Orientación sexual','identidad de género','Identidad de género','política pública para la mujer','Política pública para la mujer','políticas públicas para la mujer','Políticas públicas para la mujer','políticas públicas para las mujeres','Políticas públicas para las mujeres'],
    'Población migrante': ['población migrante', 'Población migrante', 'política para la población migrante', 'Política para la población migrante', 'políticas para la población migrante', 'Políticas para la población migrante', 'personas migrantes', 'Personas migrantes', 'persona migrante', 'Persona migrante'],
    'Población étnica': ['población étnica', 'Población étnica', 'grupo étnico', 'Grupo étnico', 'política para la población étnica', 'Política para la población étnica', 'políticas para la población étnica', 'Políticas para la población étnica', 'política para los grupos étnicos', 'Política para los grupos étnicos', 'políticas para los grupos étnicos', 'Políticas para los grupos étnicos', 'indígena', 'Indígena', 'afrocolombiano', 'Afrocolombiano', 'raizal', 'Raizal', 'palenquero', 'Palenquero'],
    'Población con discapacidad': ['población con discapacidad', 'Población con discapacidad', 'poblaciones con discapacidad', 'Poblaciones con discapacidad', 'discapacitados', 'Discapacitados', 'personas con discapacidad', 'Personas con discapacidad', 'movilidad reducida', 'Movilidad reducida', 'necesidades especiales', 'Necesidades especiales'],
    'Servicios culturales, artisticos y deportivos': ['servicios culturales, artisticos y deportivos', 'Servicios culturales, artisticos y deportivos', 'servicios culturales', 'Servicios culturales', 'servicios artísticos', 'Servicios artísticos', 'servicios deportivos', 'Servicios deportivos', 'servicio cultural', 'Servicio cultural', 'servicio artístico', 'Servicio artístico', 'servicio deportivo', 'Servicio deportivo','cultura','Cultura','deporte y recreación','Deporte y recreación','el deporte y la recreación','El deporte y la recreación'],
    'Infraestructura cultural, artistica y deportiva': ['infraestructura cultural, artistica y deportiva', 'Infraestructura cultural, artistica y deportiva', 'infraestructura cultural', 'Infraestructura cultural', 'infraestructura artística', 'Infraestructura artística', 'infraestructura deportiva', 'Infraestructura deportiva', 'estadio', 'Estadio', 'cancha', 'Cancha', 'teatro', 'Teatro','Infraestructura para el deporte','infraestructura para el deporte','Infraestructura para la recreación','infraestructura para la recreación','infraestructura deportiva','Infraestructura deportiva','centro de formación deportiva','Centro de formación deportiva','centro deportivo','Centro deportivo'],
    'Parques y espacios públicos': ['parques y espacios públicos', 'Parques y espacios públicos', 'parques', 'Parques', 'espacio público', 'Espacio público', 'espacios públicos', 'Espacios públicos', 'zona verde', 'Zona verde', 'zonas verdes', 'Zonas verdes', 'zona de esparcimiento', 'Zona de esparcimiento', 'zonas de esparcimiento', 'Zonas de esparcimiento', 'lugar de esparcimiento', 'Lugar de esparcimiento', 'lugares de esparcimiento', 'Lugares de esparcimiento'],
    'Estímulos y apoyos cultura, recreación y deporte': ['estímulos y apoyos cultura, recreación y deporte', 'Estímulos y apoyos cultura, recreación y deporte', 'estímulos y apoyos para la cultura', 'Estímulos y apoyos para la cultura', 'estímulo a la cultura', 'Estímulo a la cultura', 'estímulos a la cultura', 'Estímulos a la cultura', 'apoyo a la cultura', 'Apoyo a la cultura', 'apoyos a la cultura', 'Apoyos a la cultura', 'estímulo para la cultura', 'Estímulo para la cultura', 'estímulos para la cultura', 'Estímulos para la cultura', 'apoyo para la cultura', 'Apoyo para la cultura', 'apoyos para la cultura', 'Apoyos para la cultura', 'estímulo a la recreación', 'Estímulo a la recreación', 'estímulos a la recreación', 'Estímulos a la recreación', 'apoyo a la recreación', 'Apoyo a la recreación', 'apoyos a la recreación', 'Apoyos a la recreación', 'estímulo para la recreación', 'Estímulo para la recreación', 'estímulos para la recreación', 'Estímulos para la recreación', 'apoyo para la recreación', 'Apoyo para la recreación', 'apoyos para la recreación', 'Apoyos para la recreación', 'estímulo al deporte', 'Estímulo al deporte', 'estímulos al deporte', 'Estímulos al deporte', 'apoyo al deporte', 'Apoyo al deporte', 'apoyos al deporte', 'Apoyos al deporte', 'estímulo para el deporte', 'Estímulo para el deporte', 'estímulos para el deporte', 'Estímulos para el deporte', 'apoyo para el deporte', 'Apoyo para el deporte', 'apoyos para el deporte', 'Apoyos para el deporte','procesos culturales','Procesos culturales','procesos artísticos','Procesos artísticos','artes','Artes', 'artística','Artística','creativa','Creativa'],
    'Bibliotecas públicas': ['bibliotecas públicas', 'Bibliotecas públicas', 'biblioteca pública', 'Biblioteca pública','Bibliotecas Públicas','biblioteca','bibliotecas','Biblioteca','Bibliotecas'],
    'Cuidado y conservación de bienes de interés general y patrimonio': [ 'Cuidado de bienes de interés general ',  'cuidado de bienes de interés general ',  'Conservación de bienes de interés general ',  'conservación de bienes de interés general ',  'Patrimonio ',  'patrimonio '],
    'Turismo, hotelería y gastronomía': [ 'Turismo ',  'turismo ',  'Hotelería ',  'hotelería ',  'Gastronomía ',  'gastronomía ',  'Turismo y hoteleria ',  'turismo y hoteleria ',  'Turismo y gastronomía ',  'turismo y gastronomía ',  'Turismo & gastronomía ',  'turismo & gastronomía ',  'Servicios turísticos ',  'servicios turísticos ',  'Servicios hoteleros ',  'servicios hoteleros ',  'Turismo sostenible ',  'turismo sostenible ',  'Hoteleria y gastronomia ',  'hoteleria y gastronomia ',  'Restaurantes ',  'restaurantes ',  'Catering ',  'catering ',  'Servicios de alimentación ',  'servicios de alimentación ',  'Servicios de hospedaje ',  'servicios de hospedaje ',  'Alojamiento ',  'alojamiento ',  'Alojamientos ',  'alojamientos '],
    'Mipymes (tejido empresarial)': [ 'PYMES ',  'pymes ',  'MIPYMES ',  'mipymes ',  'Pequeña y mediana empresa ',  'pequeña y mediana empresa ',  'Micro empresa, pequeña empresa y empresa mediana ',  'micro empresa, pequeña empresa y empresa mediana ',  'Tejido empresarial ',  'tejido empresarial ',  'Micro, pequeñas y medianas empresas ',  'micro, pequeñas y medianas empresas', 'emprendimiento', 'pequeño comercio', 'pequeños comerciantes', 'microempresario', 'medianos empresarios','Emprendimiento', 'Pequeño comercio', 'Pequeños comerciantes', 'Microempresario', 'Medianos empresarios'],
    'Clústers (alianzas público privadas)': [ 'Cluster ',  'cluster ',  'Clusters ',  'clusters ',  'Alianzas público privadas ',  'alianzas público privadas ',  'Alianzas privadas y públicas ',  'alianzas privadas y públicas ',  'APP ',  'app ',  'Alianza público-privada ',  'alianza público-privada ',  'Agrupamiento ',  'agrupamiento ',  'Asociación ',  'asociación ',  'Asociatividad ',  'asociatividad ',  'Red de empresas ',  'red de empresas '],
    'Economía popular': [ 'economía popular','Economía popular','Economía social ',  'economía social ',  'Ferias ',  'ferias ',  'Venta ambulante ',  'venta ambulante ',  'Ventas ambulantes ',  'ventas ambulantes ',  'Unidades económicas populares ',  'unidades económicas populares ',  'Cooperativas de trabajo ',  'cooperativas de trabajo ',  'Agrupaciones de microemprendedores ',  'agrupaciones de microemprendedores ',  'Emprendimientos comunitarios ',  'emprendimientos comunitarios ',  'Clubes de trueque ',  'clubes de trueque ',  'Mercados asociativos populares ',  'mercados asociativos populares ',  'Redes de comercio justo ',  'redes de comercio justo ',  'Organizaciones de microcrédito ',  'organizaciones de microcrédito ',  'Empresas recuperadas ',  'empresas recuperadas ',  'Redes de consumo responsable ',  'redes de consumo responsable ',  'Grupos comunitarios de base ',  'grupos comunitarios de base ',  'Medios de comunicación comunitarios ',  'medios de comunicación comunitarios ',  'Núcleos de agricultura familiar ',  'núcleos de agricultura familiar ',  'Comunidades de pueblos originarios ',  'comunidades de pueblos originarios','informalidad','Informalidad','vendedor informal','Vendedor informal','vendedores informales','Vendedores informales'],
    'Innovación y emprendimiento': [ 'Emprendimiento ',  'emprendimiento ',  'Innovación ',  'innovación ',  'Innovación abierta ',  'innovación abierta ',  'Innovación social ',  'innovación social ',  'Emprendedurismo ',  'emprendedurismo ',  'Innovaciones ',  'innovaciones ',  'Startup ',  'startup ',  'Startups ',  'startups ',  'Espacios de innovación ',  'espacios de innovación ',  'Espacios de emprendimiento ',  'espacios de emprendimiento '],
    'TIC (desarrollo, competitividad)': [ 'Desarrollo ',  'desarrollo ',  'Competitividad ',  'competitividad ',  'Tecnologías de la información y la comunicación ',  'tecnologías de la información y la comunicación ',  'Tecnologías de la información y las comunicaciones ',  'tecnologías de la información y las comunicaciones ',  'Informática ',  'informática ',  'Tecnología ',  'tecnología ',  'Sistematización ',  'sistematización ',  'Transformación digital ',  'transformación digital ',  'Nuevas tecnologías ',  'nuevas tecnologías ',  'Era digital ',  'era digital ',  'Interconectividad ',  'interconectividad ',  'Competitividad estratégica ',  'competitividad estratégica '],
    'Agroindustria': [ 'Agronegocios ',  'agronegocios ',  'Industria agrícola ',  'industria agrícola ',  'Industria agroalimentaria ',  'industria agroalimentaria ',  'Industria agropecuaria ',  'industria agropecuaria ',  'Industria alimentaria ',  'industria alimentaria ',  'Industria alimenticia ',  'industria alimenticia ',  'Sector agroalimentario ',  'sector agroalimentario ',  'Agroalimentario ',  'agroalimentario '],
    'Economía informal (ventas ambulantes e informalidad laboral) ': [ 'Economía informal ',  'economía informal ',  'Sector informal ',  'sector informal ',  'Informalidad ',  'informalidad ',  'Economía oculta ',  'economía oculta ',  'Economía sumergida ',  'economía sumergida ',  'Ventas ambulantes ',  'ventas ambulantes ',  'Vendedores informales ',  'vendedores informales ',  'Informalidad laboral ',  'informalidad laboral '],
    'Plazas de mercado': [ 'Plaza de mercado ',  'plaza de mercado ',  'Plazas de mercado ',  'plazas de mercado ',  'Plazas ',  'plazas ',  'Centro de abastecimiento ',  'centro de abastecimiento ',  'Centro de abastecimiento alimenticio ',  'centro de abastecimiento alimenticio '],
    'Inversión extranjera ': [ 'Inversión extranjera ',  'inversión extranjera ',  'Capital extranejero ',  'capital extranejero ',  'Participación extranjera ',  'participación extranjera ',  'Inversiones extranjeras ',  'inversiones extranjeras ',  'Capitales extranjeros ',  'capitales extranjeros ',  'Participaciones extranjeras ',  'participaciones extranjeras '],
    'Formación para el trabajo': [ 'Formación para el trabajo ',  'formación para el trabajo ',  'Formaciones para el trabajo ',  'formaciones para el trabajo ',  'Capacitación laboral ',  'capacitación laboral ',  'Formación profesional ',  'formación profesional ',  'Enseñanza profesional ',  'enseñanza profesional ',  'Entrenamiento para el trabajo ',  'entrenamiento para el trabajo ',  'Educación para el trabajo ',  'educación para el trabajo ',  'Formación para trabajar ',  'formación para trabajar ',  'Capacitaciones para trabajar ',  'capacitaciones para trabajar ',  'Entrenamiento para trabajar ',  'entrenamiento para trabajar '],
    'Empleo juvenil': [ 'Empleo juvenil ',  'empleo juvenil ',  'Empleo para los jóvenes ',  'empleo para los jóvenes ',  'Trabajo para los jóvenes ',  'trabajo para los jóvenes ',  'Trabajo para la juventud ',  'trabajo para la juventud ',  'Trabajo decente para los jóvenes ',  'trabajo decente para los jóvenes ',  'Inserción laboral para los jóvenes ',  'inserción laboral para los jóvenes ',  'Primer empleo ',  'primer empleo '],
    'Estrategias de generación de empleo': ['empleo','emprendimiento','empresariado','Empleo','Emprendimiento','Empresariado', 'Estrategias de generación de empleo ',  'estrategias de generación de empleo ',  'Estrategia de generación de empleo ',  'estrategia de generación de empleo ',  'Estrategias de generación de trabajos ',  'estrategias de generación de trabajos ',  'Estrategia de generación de trabajo ',  'estrategia de generación de trabajo ',  'Creación de empleo ',  'creación de empleo ',  'Creación de empleos ',  'creación de empleos ',  'Estrategias de empleo ',  'estrategias de empleo ',  'Generación de empleo ',  'generación de empleo ',  'Generación de trabajo ',  'generación de trabajo ',  'Generación de trabajos ',  'generación de trabajos '],
    'Estímulos tributarios (impuestos, predial)': [ 'Incentivos fiscales ',  'incentivos fiscales ',  'Bonificaciones tributarias ',  'bonificaciones tributarias ',  'Descuentos en impuestos ',  'descuentos en impuestos ',  'Reducciones fiscales ',  'reducciones fiscales ',  'Beneficios tributarios ',  'beneficios tributarios ',  'Impuesto predial ',  'impuesto predial ',  'Impuestos prediales ',  'impuestos prediales '],
    'Gobierno digital y trámites': [ 'Administración electrónica ',  'administración electrónica ',  'Gobierno en línea ',  'gobierno en línea ',  'Digitalización administrativa ',  'digitalización administrativa ',  'Trámites en línea ',  'trámites en línea ',  'Servicios digitales ',  'servicios digitales ',  'Gobierno digital ',  'gobierno digital ',  'Trámites ',  'trámites '],
    'Accountability y rendición de cuentas (transparencia)': [ 'Responsabilidad administrativa ',  'responsabilidad administrativa ',  'Transparencia ',  'transparencia ',  'Rendición de cuentas ',  'rendición de cuentas ',  'Control social ',  'control social ',  'Supervisión ',  'supervisión ',  'Vigilancia ',  'vigilancia '],
    'Atención a la ciudadanía ': [ 'Servicio al ciudadano ',  'servicio al ciudadano ',  'Atención al público ',  'atención al público ',  'Orientación ciudadana ',  'orientación ciudadana ',  'Soporte ciudadano ',  'soporte ciudadano ',  'Interacción ciudadana ',  'interacción ciudadana ',  'Servicio a la ciudadanía ',  'servicio a la ciudadanía','canal de atención','Canal de atención','canales de atención','Canales de atención'],
    'Gestión pública e innovación ': [ 'Administración estatal y cambio ',  'administración estatal y cambio ',  'Modernización del sector público ',  'modernización del sector público ',  'Innovación en la gestión pública ',  'innovación en la gestión pública ',  'Renovación administrativa ',  'renovación administrativa ',  'Transformación gubernamental ',  'transformación gubernamental '],
    'Eficiencia gasto público ': [ 'Uso eficiente de recursos públicos ',  'uso eficiente de recursos públicos ',  'Optimización del gasto estatal ',  'optimización del gasto estatal ',  'Optimización del gasto del estado ',  'optimización del gasto del estado ',  'Ahorro fiscal ',  'ahorro fiscal ',  'Racionalización del gasto ',  'racionalización del gasto ',  'Reducción del gasto público ',  'reducción del gasto público '],
    'Gestión de la Deuda pública': ['deuda','Deuda' 'Administración de pasivos del estado ',  'administración de pasivos del estado ',  'Manejo de la deuda gubernamental ',  'manejo de la deuda gubernamental ',  'Política de deuda pública ',  'política de deuda pública ',  'Gestión financiera del endeudamiento ',  'gestión financiera del endeudamiento ',  'Control de la deuda estatal ',  'control de la deuda estatal','gasto público','Gasto público','rubro','Rubro','vigencia futura','Vigencia futura','vigencias futuras','Vigencias futuras','endeudamiento','Endeudamiento'],
    'Eficiencia administrativa': [ 'Optimización de procesos administrativos ',  'optimización de procesos administrativos ',  'Mejora de la gestión burocrática ',  'mejora de la gestión burocrática ',  'Eficacia administrativa ',  'eficacia administrativa ',  'Productividad en la administración pública ',  'productividad en la administración pública ',  'Eficiencia en la gestión ',  'eficiencia en la gestión ',  'Eficiencia en la gestión pública ',  'eficiencia en la gestión pública '],
    'Defensa judicial del municipio ': [ 'Representación legal de la municipalidad ',  'representación legal de la municipalidad ',  'Asesoría jurídica municipal ',  'asesoría jurídica municipal ',  'Abogacía del municipio ',  'abogacía del municipio ',  'Litigio municipal ',  'litigio municipal ',  'Apoyo legal municipal ',  'apoyo legal municipal '],
    'Financiación de vivienda': [ 'Financiamiento para vivienda ',  'financiamiento para vivienda ',  'Créditos hipotecarios ',  'créditos hipotecarios ',  'Subsidios de vivienda ',  'subsidios de vivienda ',  'Préstamos para vivienda ',  'préstamos para vivienda ',  'Ayudas financieras para vivienda ',  'ayudas financieras para vivienda','subsidio','Subsidios'],
    'Legalización y titulación (barrios- asentamientos) ': [ 'Regularización y formalización (barrios- asentamientos) ',  'regularización y formalización (barrios- asentamientos) ',  'Legalización de viviendas informales ',  'legalización de viviendas informales ',  'Titulación de terrenos ocupados ',  'titulación de terrenos ocupados ',  'Legalización de asentamientos humanos ',  'legalización de asentamientos humanos ',  'Formalización de barrios marginales ',  'formalización de barrios marginales ',  'Barrios y asentamientos informales ',  'barrios y asentamientos informales ',  'Barrios y asentamientos ilegales ',  'barrios y asentamientos ilegales '],
    'Vivienda Social (VIS Y VIP)': [ 'Vivienda de interés social (VIS) ',  'vivienda de interés social (VIS) ',  'Vivienda de interés prioritario (VIP) ',  'vivienda de interés prioritario (VIP) ',  'Programas de vivienda subsidiada ',  'programas de vivienda subsidiada ',  'Hogares de bajos ingresos ',  'hogares de bajos ingresos ',  'Soluciones habitacionales asequibles ',  'soluciones habitacionales asequibles ',  'VIS y VIP ',  'vis y vip ',  'VIS ',  'vis ',  'VIP ',  'vip ',  'Vivienda de interés social y vivienda de interés prioritario ',  'vivienda de interés social y vivienda de interés prioritario '],
    'Revitalización / renovación urbana': [ 'Rehabilitación urbana ',  'rehabilitación urbana ',  'Reactivación de áreas urbanas ',  'reactivación de áreas urbanas ',  'Renovación de espacios urbanos ',  'renovación de espacios urbanos ',  'Mejora de barrios degradados ',  'mejora de barrios degradados ',  'Recuperación de zonas urbanas ',  'recuperación de zonas urbanas ',  'Revitalización urbana ',  'revitalización urbana ',  'Reactivación urbana ',  'reactivación urbana '],
    'Calidad y mejoramiento de la vivienda': [ 'Mejora de la calidad de la vivienda ',  'mejora de la calidad de la vivienda ',  'Acondicionamiento de las viviendas ',  'acondicionamiento de las viviendas ',  'Rehabilitación de los inmuebles ',  'rehabilitación de los inmuebles ',  'Refacción de las viviendas ',  'refacción de las viviendas ',  'Actualización de infraestructura residencial ',  'actualización de infraestructura residencial ',  'Mejoramiento de vivienda ',  'mejoramiento de vivienda ',  'Mejoramiento de la vivienda ',  'mejoramiento de la vivienda','subsidio','Subsidio','mejoramiento de vivienda','Mejoramiento de vivienda'],
    'Ocupaciones ilegales': [ 'Invasiones de tierras ',  'invasiones de tierras ',  'Asentamientos informales ',  'asentamientos informales ',  'Asentamientos precarios ',  'asentamientos precarios ',  'Ocupación irregular de terrenos ',  'ocupación irregular de terrenos ',  'Asentamientos ilegales ',  'asentamientos ilegales','zona de origen informal','Zona de origen informal','zonas de origen informal','Zonas de origen informal'],
    'Disposición final de residuos sólidos': ['Residuos sólidos','residuos sólidos','Residuos de Construcción y Demolición','Residuos de construcción y demolición','residuos de construcción y demolición' ,'Eliminación de residuos sólidos ',  'eliminación de residuos sólidos ',  'Tratamiento de basura ',  'tratamiento de basura ',  'Gestión de desechos sólidos ',  'gestión de desechos sólidos ',  'Eliminación de desechos sólidos ',  'eliminación de desechos sólidos ',  'Vertedero de basura ',  'vertedero de basura ',  'Vertederos de basura ',  'vertederos de basura','gestión de residuos','Gestión de residuos'],
    'Agua y alcantarillado': [ 'Servicios de agua potable y saneamiento ',  'servicios de agua potable y saneamiento ',  'Suministro de agua y sistemas de alcantarillado ',  'suministro de agua y sistemas de alcantarillado ',  'Infraestructura hídrica ',  'infraestructura hídrica ',  'Abastecimiento de agua y redes de alcantarillado ',  'abastecimiento de agua y redes de alcantarillado ',  'Tratamiento de aguas residuales ',  'tratamiento de aguas residuales ',  'Aguas residuales ',  'aguas residuales '],
    'Conectividad digital': [ 'Acceso a internet ',  'acceso a internet ',  'Conexión digital ',  'conexión digital ',  'Infraestructura de las comunicaciones ',  'infraestructura de las comunicaciones ',  'Redes de telecomunicaciones ',  'redes de telecomunicaciones ',  'Servicios de conexión a internet ',  'servicios de conexión a internet','conectividad','Conectividad'],
    'Alumbrado público': [ 'Iluminación urbana ',  'iluminación urbana ',  'Sistema de alumbrado ',  'sistema de alumbrado ',  'Alumbrado de calles ',  'alumbrado de calles ',  'Luminarias públicas ',  'luminarias públicas ',  'Red de iluminación exterior ',  'red de iluminación exterior ',  'Sistema de alumbrado público ',  'sistema de alumbrado público ',  'Alumbrado público ',  'alumbrado público '],
    'PTAR (planta de tratamiento de aguas residuales) ': [ 'Estación depuradora de aguas residuales (EDAR) ',  'estación depuradora de aguas residuales (EDAR) ',  'Planta de tratamiento de aguas servidas ',  'planta de tratamiento de aguas servidas ',  'Depuradora de aguas residuales ',  'depuradora de aguas residuales ',  'Tratamiento de aguas usadas ',  'tratamiento de aguas usadas ',  'Planta de tratamiento de aguas grises ',  'planta de tratamiento de aguas grises '],
    'POT y Desarrollo urbano (actualización, modificación)': [ 'Plan de ordenamiento territorial (POT) ',  'plan de ordenamiento territorial (POT) ',  'Planeación urbana ',  'planeación urbana ',  'Planificación del desarrollo urbano ',  'planificación del desarrollo urbano ',  'Ordenamiento del territorio ',  'ordenamiento del territorio ',  'Política de desarrollo urbano ',  'política de desarrollo urbano ',  'POT ',  'pot ',  'Ordenamiento territorial ',  'ordenamiento territorial ',  'Actualización y modificación del POT ',  'actualización y modificación del POT'],
    'Gestión del riesgo y atención de desastres': [ 'Prevención de desastres ',  'prevención de desastres ',  'Mitigación de riesgos ',  'mitigación de riesgos ',  'Gestión de emergencias ',  'gestión de emergencias ',  'Resiliencia urbana ',  'resiliencia urbana ',  'Atención a las catástrofes ',  'atención a las catástrofes '],
    'Espacio Público (accesibilidad, ocupación y aprovechamiento)': [ 'Áreas públicas ',  'áreas públicas ',  'Zonas de recreación ',  'zonas de recreación ',  'Plazas y parques ',  'plazas y parques ',  'Vías peatonales ',  'vías peatonales ',  'Entornos urbanos ',  'entornos urbanos ',  'Parques ',  'parques ',  'Ciclovías ',  'ciclovías ',  'Accesibilidad, ocupación y aprovechamiento ',  'accesibilidad, ocupación y aprovechamiento '],
    'Obras por valorización ': [ 'Infraestructura financiada por la valorización ',  'infraestructura financiada por la valorización ',  'Obras públicas financiadas por las contribuciones especiales ',  'obras públicas financiadas por las contribuciones especiales ',  'Mejoras financiadas por las contribuciones de valorización ',  'mejoras financiadas por las contribuciones de valorización ',  'Inversiones a cargo de los beneficiarios ',  'inversiones a cargo de los beneficiarios ',  'Proyectos cofinanciados por la comunidad ',  'proyectos cofinanciados por la comunidad'],
    'Plusvalía y gestión del suelo ': [ 'Valorización de terrenos ',  'valorización de terrenos ',  'Incremento de la plusvalía ',  'incremento de la plusvalía ',  'Aumento del valor del suelo ',  'aumento del valor del suelo ',  'Política de gestión del suelo ',  'política de gestión del suelo ',  'Valorización inmobiliaria ',  'valorización inmobiliaria '],
    'Control urbanístico y usos del suelo (construcciones)': [ 'Regulación del uso del suelo ',  'regulación del uso del suelo ',  'Normativa urbanística ',  'normativa urbanística ',  'Planificación de construcciones ',  'planificación de construcciones ',  'Ordenamiento territorial ',  'ordenamiento territorial ',  'Zonificación urbana ',  'zonificación urbana '],
    'Territorio Inteligente (Smartcity)': [ 'Ciudad inteligente ',  'ciudad inteligente ',  'Urbanismo digital ',  'urbanismo digital ',  'Desarrollo de territorios inteligentes ',  'desarrollo de territorios inteligentes ',  'Infraestructura tecnológica urbana ',  'infraestructura tecnológica urbana ',  'Smart city',  'smart city','territorio inteligente','Territorio inteligente'],
    'Actualización catastral (catastro multipropósito)': [ 'Actualización del catastro ',  'actualización del catastro ',  'Renovación catastral ',  'renovación catastral ',  'Revisión del registro de propiedades ',  'revisión del registro de propiedades ',  'Actualización de datos catastrales ',  'actualización de datos catastrales ',  'Revaluación del catastro ',  'revaluación del catastro ',  'Catastro multipropósito ',  'catastro multipropósito ',  'Actualización catastral ',  'actualización catastral', 'catastral','Catastral'],
    'Cargas y beneficios para el desarrollo inmobiliario': ['Contribuciones urbanísticas', 'contribuciones urbanísticas', 'Impuestos a la construcción', 'impuestos a la construcción', 'Cánones de urbanización', 'cánones de urbanización', 'Cargas y beneficios por desarrollo urbano', 'cargas y beneficios por desarrollo urbano', 'Tasas por aprovechamiento del suelo', 'tasas por aprovechamiento del suelo','obligaciones','desarrollo inmobiliario','Desarrollo inmobiliario','desarrollador inmobiliario','Desarrollador inmobiliario','desarrolladores inmobiliarios','Desarrolladores inmobiliarios','habilitación del suelo','Habilitación del suelo'],
    'Ordenamiento regional': ['Planificación regional', 'planificación regional', 'Organización territorial', 'organización territorial', 'Coordinación regional', 'coordinación regional', 'Ordenamiento del territorio', 'ordenamiento del territorio', 'Desarrollo regional', 'desarrollo regional'],
    'Seguridad regional': ['Protección regional', 'protección regional', 'Seguridad en la región', 'seguridad en la región', 'Prevención del delito a nivel regional', 'prevención del delito a nivel regional', 'Control de la delincuencia en la región', 'control de la delincuencia en la región', 'Cooperación en seguridad regional', 'cooperación en seguridad regional'],
    'Transporte público': ['Transporte colectivo', 'transporte colectivo', 'Transporte masivo', 'transporte masivo', 'Movilidad urbana', 'movilidad urbana', 'Servicio de transporte público', 'servicio de transporte público', 'Sistema de transporte público', 'sistema de transporte público'],
    'Región metropolitana (Vinculación institucional)': ['Área metropolitana', 'área metropolitana', 'Zona metropolitana', 'zona metropolitana', 'Conurbación', 'conurbación', 'Región urbana', 'región urbana', 'Área metropolitana integrada', 'área metropolitana integrada', 'Región metropolitana', 'región metropolitana'],
    'Proyectos intermunicipales': ['Proyectos regionales', 'proyectos regionales', 'Iniciativas intermunicipales', 'iniciativas intermunicipales', 'Desarrollos conjuntos', 'desarrollos conjuntos', 'Proyectos colaborativos', 'proyectos colaborativos', 'Iniciativas intergubernamentales', 'iniciativas intergubernamentales'],
    'Competitividad regional': ['Desarrollo económico regional', 'desarrollo económico regional', 'Productividad a nivel regional', 'productividad a nivel regional', 'Fortalecimiento de la economía regional', 'fortalecimiento de la economía regional', 'Competitividad territorial', 'competitividad territorial', 'Dinamización regional', 'dinamización regional'],
    'Abastecimiento regional (centro de acopio)': ['abastecimiento regional','Abastecimiento regional','Abastecimiento en la región','abastecimiento en la región','centro de acopio','Centro de acopio','Suministro regional', 'suministro regional', 'Distribución regional', 'distribución regional', 'Logística de abastecimiento', 'logística de abastecimiento', 'Centro logístico regional', 'centro logístico regional', 'Almacenamiento y distribución regional', 'almacenamiento y distribución regional'],
    'Abastecimiento y distribución': ['Abastecimiento ', 'abastecimiento ', 'Cadena de abastecimiento ', 'cadena de abastecimiento ', 'Suministro', 'suministro', 'Cadena de suministros', 'cadena de suministros', 'Distribución ', 'distribución ', 'Cadena de distribución ', 'cadena de distribución ', 'Acopio ', 'acopio ', 'Aprovisionamiento', 'aprovisionamiento', 'Almacenamiento', 'almacenamiento', 'Logística ', 'logística ', 'Supply chain', 'supply chain', 'Cadena de suministro', 'cadena de suministro', 'Rutas de distribución ', 'rutas de distribución '],
    'Educación rural': ['Educación rural ', 'educación rural ', 'Ruralidad', 'ruralidad', 'Formación rural ', 'formación rural ', 'Educación de la población rural', 'educación de la población rural', 'Escuela rural ', 'escuela rural ', 'Progreso rural ', 'progreso rural ', 'Educación al campo ', 'educación al campo ', 'Educación media rural ', 'educación media rural ', 'Educación formal rural', 'educación formal rural', 'Escuelas rurales', 'escuelas rurales', 'Escuelas en el medio rural', 'escuelas en el medio rural', 'Instituciones educativas rurales ', 'instituciones educativas rurales '],
    'Protección social del campesino ': ['Capital social campesino ', 'capital social campesino ', 'Protección social y campesinos ', 'protección social y campesinos ', 'Capital social del agricultor ', 'capital social del agricultor ', 'Capital social de la campesina ', 'capital social de la campesina ', 'Capital social y campesinas ', 'capital social y campesinas ', 'Protección social de las campesinas', 'protección social de las campesinas', 'Protección social de los campesinos ', 'protección social de los campesinos ', 'Protección social y campesina ', 'protección social y campesina ', 'Protección social y campesinas', 'protección social y campesinas', 'Cápital social rural', 'cápital social rural'],
    'Mujeres campesinas': ['Mujer campesina', 'mujer campesina', 'Mujer del agro ', 'mujer del agro ', 'Mujeres del agro ', 'mujeres del agro ', 'Mujer agricultora ', 'mujer agricultora ', 'Mujeres agricultoras ', 'mujeres agricultoras ', 'Mujer rural', 'mujer rural', 'Mujeres rurales ', 'mujeres rurales ', 'Mujeres en la ruralidad ', 'mujeres en la ruralidad ', 'Campesina ', 'campesina ', 'Campesinas', 'campesinas'],
    'Producción agrícola': ['Producción de la agricultura ', 'producción de la agricultura ', 'Producción del agro ', 'producción del agro ', 'Cultivo ', 'cultivo ', 'Cultivos ', 'cultivos ', 'Producción agraria ', 'producción agraria ', 'Agricultura sostenible', 'agricultura sostenible', 'Agricultura inteligente ', 'agricultura inteligente ', 'Producción de alimentos', 'producción de alimentos', 'Producción agrícola', 'producción agrícola', 'Agricultura de precisión ', 'agricultura de precisión ', 'Agricultura industrial', 'agricultura industrial', 'Maquinaria agrícola', 'maquinaria agrícola', 'Tecnología agrícola', 'tecnología agrícola'],
    'Salud rural': ['Salud en la ruralidad ', 'salud en la ruralidad ', 'Salud en el campo ', 'salud en el campo ', 'Salud rural ', 'salud rural ', 'Ciencias de la salud  en el campo ', ' ciencias de la salud  en el campo ', ' Ciencias de la salud en la ruralidad', ' ciencias de la salud en la ruralidad', 'Ciencias de la salud rurales ', ' ciencias de la salud rurales '],
    'Mercados campesinos ': ['Mercado de productores ', 'mercado de productores ', 'Mercado de agricultores', 'mercado de agricultores', 'Mercado agrícola ', 'mercado agrícola ', 'Mercado campesino ', 'mercado campesino ', 'Mercado verde ', 'mercado verde ', 'El campo a la ciudad ', 'el campo a la ciudad ', 'Mercados locales campesinos ', 'mercados locales campesinos ', 'Mercados verdes ', 'mercados verdes '],
    'Infraestructura rural ': ['Infraestructuras rurales ', 'infraestructuras rurales ', 'Infraestructura del campo ', 'infraestructura del campo ', 'Infraestructura de la ruralidad ', 'infraestructura de la ruralidad ', ' Infraestructura de lo rural', ' infraestructura de lo rural', 'Desarrollo de la infraestructura rural ', 'desarrollo de la infraestructura rural ', 'Desarrollo de la infraestructura en la ruralidad', 'desarrollo de la infraestructura en la ruralidad'],
    'Participación infantil y juvenil': ['Participación de los jóvenes', 'participación de los jóvenes', 'Participación infantil', 'participación infantil', 'Participación de las niñas', 'participación de las niñas', 'Participación de los niños ', 'participación de los niños ', 'Participación de los adolescentes', 'participación de los adolescentes', 'Participación de la infancia', 'participación de la infancia', 'Participación de las juventudes ', 'participación de las juventudes ', ' Participación juvenil', 'participación juvenil','niño','Niño','niña','Niña','adolescente','Adolescente','jóven','Jóven'], 
    'Población LGBTIQ+': ['Participación población LGBTIQ+', 'participación población LGBTIQ+', 'Participación población LGTB', 'participación población lgtb', 'Participación población LGT', 'participación población lgt', 'Participación lgbti+ ', 'participación lgbti+ ', 'Participación lgt ', 'participación lgt ', 'Participación de lesbianas', 'participación de lesbianas', 'Participación de gays ', 'participación de gays ', 'Participación de bisexuales', 'participación de bisexuales', 'Participación de transgenero', 'participación de transgenero', 'Participación de transexuales', 'participación de transexuales', ' Participación de travestis', 'participación de travestis', 'Participación de transformistas', 'participación de transformistas', 'Participación de intersexuales', 'participación de intersexuales','comunidad LGBT','Comunidad LGBT','comunidades LGBT','Comunidades LGBT'],
    'Comunidades étnicas': ['comunidad étnicas','Comunidad étnica','comunidades étnicas','Comunidades étnicas','grupo étnico','Grupo étnico','grupos étnicos','Grupos étnicos','Participación de comunidades de grupos étnicos ', 'participación de comunidades de grupos étnicos ', 'Participación de indigenas ', 'participación de indigenas ', 'Participación de afrocolombianos ', 'participación de afrocolombianos ', 'Participación de afrodescendientes ', 'participación de afrodescendientes ', 'Participación de negros', 'participación de negros', 'Participación de mulatos', 'participación de mulatos', 'Participación de palenqueros de san basilio ', 'participación de palenqueros de san basilio ', 'Participación de raizales', 'participación de raizales', 'Participación de comunidades indigenas', 'participación de comunidades indigenas', 'Participación de rom ', 'participación de rom ', 'Participación de gitano ', 'participación de gitano ', 'Pueblo indigena', 'pueblo indigena', 'Participación de raizal del archipielago de san andres y providencia', 'participación de raizal del archipielago de san andres y providencia', 'Resguardo indígena','resguardo indígena','Resguardos indígenas','resguardos indígenas'],
    'Veedurías ciudadanas ': ['Vigilancia de la ciudadanía', 'vigilancia de la ciudadanía', 'Vigilancia ciudadana', 'vigilancia ciudadana', 'Veeduría de los ciudadanos', 'veeduría de los ciudadanos', 'Mecanismo de control social de los ciudadanos', 'mecanismo de control social de los ciudadanos ', 'Participación de la vigilancia de la ciudadanía ', ' participación de la vigilancia de la ciudadanía ', ' Participación de la veeduría de los ciudadanos', ' participación de la veeduría de los ciudadanos'], 
    'Formación y capacitación ciudadana ': ['Formación ciudadana ', 'formación ciudadana ', 'Capacitación ciudadana ', 'capacitación ciudadana ', 'Educación ciudadana ', 'educación ciudadana ', ' Participación de la ciudadanía para la formación', ' participación de la ciudadanía para la formación', 'Formación de la ciudadanía', 'formación de la ciudadanía', 'Capacitación de los ciudadanos', 'capacitación de los ciudadanos', 'Formación a los ciudadanos', 'formación a los ciudadanos', ' Formación para los ciudadanos'], 
    'Presupuestos participativos': ['Presupuesto participativo', 'presupuesto participativo','Presupuestos participativos', 'presupuestos participativos', 'Presupuesto participativo municipal', 'presupuesto participativo municipal', 'Presupuesto participativo del municipio ', 'presupuesto participativo del municipio ', 'Presupuesto participativo público ', 'presupuesto participativo público '],
    'Órganos formales de participación ciudadana (JAC, Consejos -territoriales, mujeres, campesinos, juventud-, tercera edad etc.)': ['Mecanismos de participación ciudadana ', 'mecanismos de participación ciudadana ', 'JAC', 'consejos -territoriales, mujeres, campesinos, juventud-, tercera edad etc.', 'Consejos territoriales', 'consejos territoriales', 'Referendo', 'referendo', 'Referendo derogatorio', 'referendo derogatorio', ' Referendo aprobatorio', ' referendo aprobatorio', 'Revocatoria del mandato', 'revocatoria del mandato', 'Plebiscito ', 'plebiscito ', ' Consulta popular', ' consulta popular', 'Cabildo abierto', 'cabildo abierto', 'Consejos territoriales de mujeres', 'consejos territoriales de mujeres', 'Consejos territoriales de campesinos', 'consejos territoriales de campesinos', 'Consejos territoriales de juventud', 'consejos territoriales de juventud', 'Consejos territoriales de tercera edad', 'consejos territoriales de tercera edad']
    # Add more categories and words as needed
}
paragraph_color = (0, 1, 0)  # Green color for highlighted paragraphs

highlight_paragraphs_with_words(pdf_path, words_to_highlight, paragraph_color)
